// vue_test/ts_vue_project/src/App.vue
<script>
import { RouterView } from "vue-router";
import NavBar from "./components/NavBar.vue";

export default {
  data() {
    return {};
  },

  methods: {},

  components: {
    RouterView,
    NavBar,
  },
};
</script>

<template>
  <NavBar />
  <RouterView />
</template>

<style scoped lang="scss"></style>

<!-- top_rated <- type expample -->

// movie-app/src/App.jsx
import "./App.scss";
import Hero from "./components/Hero/Hero";
import MainSection from "./components/MainSection";
import NavBar from "./components/NavBar/NavBar";

function App() {
  return (
    <div className="App">
      <NavBar />
      <Hero />
      <MainSection />
    </div>
  );
}

export default App;
